volumes:
  food_data_prod:
  static_volume:
  media_volume:

services:
  food_db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - food_data_prod:/var/lib/postgresql/data
  backend:
    image: babybeardocker/food_back
    env_file: .env
    depends_on:
      - food_db
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
  frontend:
    image: babybeardocker/food_front
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: babybeardocker/food_gate
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/app/media
      - ./docs:/docs
    ports:
      - "8500:80"
    depends_on:
      - backend
    restart: always
